#!/usr/bin/env node
// Bundle the MCP server and its runtime dependencies into dist/server.mjs so
// installed plugins start without node_modules or a runtime `npm ci`.
//
//   node scripts/build.mjs          write dist/server.mjs
//   node scripts/build.mjs --check  rebuild in memory, fail if dist/ is stale
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outfile = path.join(root, "dist", "server.mjs");
const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
const check = process.argv.includes("--check");

const result = await build({
  absWorkingDir: root,
  entryPoints: ["src/server.js"],
  outfile,
  bundle: true,
  write: false,
  format: "esm",
  platform: "node",
  target: "node20",
  // ws loads these optional native accelerators with a guarded require().
  // Keeping them external preserves that guard: when they are absent the
  // require throws and ws falls back to its pure-JS implementation.
  external: ["bufferutil", "utf-8-validate"],
  define: {
    __AGENT_LINK_VERSION__: JSON.stringify(pkg.version)
  },
  // CommonJS dependencies (ws) call require() for Node built-ins; give the
  // ESM bundle a real require so those calls resolve.
  banner: {
    js: [
      "// Generated by scripts/build.mjs. Do not edit; run `npm run build`.",
      "import { createRequire as __agentLinkCreateRequire } from \"node:module\";",
      "const require = __agentLinkCreateRequire(import.meta.url);"
    ].join("\n")
  },
  legalComments: "eof",
  logLevel: "warning"
});

const output = result.outputFiles.find((file) => file.path === outfile);
if (!output) {
  throw new Error(`esbuild produced no output for ${outfile}`);
}

if (check) {
  const current = existsSync(outfile) ? readFileSync(outfile, "utf8") : null;
  if (current !== output.text) {
    console.error(`${path.relative(root, outfile)} is out of date. Run \`npm run build\` and commit the result.`);
    process.exit(1);
  }
  console.log(`${path.relative(root, outfile)} is up to date (${output.contents.length} bytes, v${pkg.version}).`);
} else {
  mkdirSync(path.dirname(outfile), { recursive: true });
  writeFileSync(outfile, output.text);
  console.log(`wrote ${path.relative(root, outfile)} (${output.contents.length} bytes, v${pkg.version})`);
}
